{
 "title": "Altaro VM Backup",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(altaro_api_success,instance)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(altaro_api_success,__tenant_id__)"
    }
   },
   {
    "name": "vmname",
    "label": "vmname",
    "query": {
     "query": "label_values(altaro_lastbackup_result,vmname)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(altaro_lastbackup_result,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Altaro API Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "altaro_api_success{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Backup Duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "altaro_lastbackup_duration_seconds{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Backup Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "altaro_lastbackup_transfersize_compressed_bytes{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}\\{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Backup Results",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "altaro_lastbackup_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\",altaro_lastbackup_result=\"Success\"}",
     "legendFormat": "{{hostname}}\\{{vmname}}"
    },
    {
     "expr": "altaro_lastbackup_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\",altaro_lastbackup_result=\"Warning\"} == 1",
     "legendFormat": "__auto"
    },
    {
     "expr": "altaro_lastbackup_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\",altaro_lastbackup_result=\"Error\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}