{
 "title": "Hornet Security / Altaro VM Backup 2024110501",
 "tags": [ "carousel" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(altaro_api_success,instance)"
    }
   },
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(altaro_api_success,__tenant_id__)"
    }
   },
   {
    "name": "vmname",
    "label": "vmname",
    "query": {
     "query": "label_values(altaro_lastbackup_result,vmname)"
    }
   },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(altaro_lastbackup_result,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Altaro API Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "altaro_api_success{__tenant_id__=~\"$tenant\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Altaro Local backup Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0 < altaro_lastbackup_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"} < 3",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Altaro Offsite backup Failures",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "0 < altaro_lastoffsitecopy_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"} < 3",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Last Backup Duration",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "altaro_lastbackup_duration_seconds{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Backup Compressed Transfered Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "altaro_lastbackup_transfersize_compressed_bytes{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}\\{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Offsite Backup Duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "altaro_lastoffsitecopy_duration_seconds{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Offsite Backup Compressed Transfered Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "altaro_lastoffsitecopy_transfersize_compressed_bytes{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}\\{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Backup Results",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "altaro_lastbackup_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}\\{{vmname}}"
    }
   ]
  },
  {
   "title": "Last Offsite Backup Results",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "altaro_lastoffsitecopy_result{__tenant_id__=~\"$tenant\",instance=~\"$instance\",vmname=~\"$vmname\",hostname=~\"$hostname\"}",
     "legendFormat": "{{hostname}}\\{{vmname}}"
    }
   ]
  }
 ]
}